#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: photon.yml
  when: ansible_lsb.codename == 'Photon'
