#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: restart ufw
  service: name=ufw state=restarted

- name: stop ufw
  service: name=ufw state=stopped

- name: reload ufw rules
  shell: ufw disable && ufw enable

- name: disable ufw rules
  shell: ufw disable
